// ============================================================
// SHARAABI SHAAM — CONTENT FILE
// Edit anything here. Safe = always shown. Risque = risque mode only.
// ============================================================

window.GAME_CONTENT = {

  // ──────────────────────────────────────────────
  // GAME 1: NEVER HAVE I EVER — DESI EDITION
  // ──────────────────────────────────────────────
  neverHaveIEver: {
    name: "Never Have I Ever",
    tagline: "Desi Edition",
    emoji: "🍹",
    color: "#FF6B35",

    safe: [
      "Never have I ever told my parents I was at a friend's house when I was absolutely not at a friend's house",
      "Never have I ever confidently given someone wrong directions instead of admitting I had no idea",
      "Never have I ever eaten someone's tiffin at work and blamed it on someone else",
      "Never have I ever cried watching a shaadi I wasn't even invested in just because the music hit different",
      "Never have I ever pretended my phone was on silent when it was just on loud and I didn't want to talk",
      "Never have I ever told a relative 'haan aunty bilkul' with absolutely zero intention of doing that thing",
      "Never have I ever secretly judged someone's order at a restaurant and been right about it",
      "Never have I ever panic-cleaned my entire room in 4 minutes because someone was coming over",
      "Never have I ever faked knowing a person's name for an entire conversation because I forgot it",
      "Never have I ever opened the fridge, found nothing, closed it, then opened it again 30 seconds later as if something would appear",
      "Never have I ever gone to a family function just for the food and left the moment the food was over",
      "Never have I ever called myself 'on the way' while still in bed",
      "Never have I ever sniffed a shirt to decide if it's clean enough to wear again",
      "Never have I ever blamed 'the signal' on a call I intentionally disconnected",
      "Never have I ever taken a photo of someone else's food at a restaurant to pretend I also eat nice things",
      "Never have I ever used 'I have work early tomorrow' to escape a situation I didn't want to be in at all",
      "Never have I ever sent a voice note I immediately regretted because I could hear how unhinged I sounded",
      "Never have I ever googled symptoms at 1am and convinced myself I had something very serious",
      "Never have I ever read a message, fully processed it, and left it on read for two days because I didn't know how to respond",
      "Never have I ever confidently started a sentence in Hindi and quietly switched to English when I got stuck",
      "Never have I ever panic-bought something because the 'only 2 left' timer scared me",
      "Never have I ever made up an entire fake story to tell my parents about where the money went",
      "Never have I ever been the loudest person in the group to compensate for having no idea what was happening",
      "Never have I ever put something on my to-do list after already doing it just to feel the satisfaction of crossing it off",
      "Never have I ever dramatically said 'fine I'll do it myself' and then asked someone for help 10 minutes later",
      "Never have I ever showed up to a potluck with store-bought food in a home container and said I made it",
      "Never have I ever fake-laughed at a relative's joke and then explained it to someone quietly in the kitchen",
      "Never have I ever replied 'haha so true' to a message I did not read",
      "Never have I ever told someone their cooking was amazing and then went home and ate actual food",
      "Never have I ever started a workout routine, lasted three days, and announced to everyone that I'm a fitness person now",
      "Never have I ever absolutely roasted someone's life choices while doing the exact same thing",
      "Never have I ever told someone 'I'll be there in 5' from a location that is 35 minutes away",
      "Never have I ever sent a full paragraph text, got a one-word reply, and had to physically restrain myself",
      "Never have I ever screenshotted a conversation to send to a third party while still actively in that conversation",
      "Never have I ever pretended to be on a call to avoid someone I saw in public",
      "Never have I ever gone on my phone mid-argument to look something up to win and then lied about what it said",
      "Never have I ever watched someone pack too light for a trip, said nothing, and enjoyed watching it unfold",
      "Never have I ever spent 45 minutes deciding what to eat and then ordered the same thing I always order",
      "Never have I ever had a full rehearsed conversation with myself in the shower that went better than the real one",
      "Never have I ever told someone I'd call them back and never called them back and never mentioned it again",
      "Never have I ever shown up to a party and immediately scanned the room for the food before saying hi to anyone",
      "Never have I ever subtly changed the plan so it was more convenient for me and pretended it was for everyone",
      "Never have I ever accepted a LinkedIn connection from someone I've never spoken to just to see their job title",
      "Never have I ever given a completely made-up excuse for being late that required more lies to maintain",
      "Never have I ever mispronounced a word I've only ever read and said it confidently to an actual human",
      "Never have I ever asked 'what's wrong?' and hoped they'd say 'nothing'",
      "Never have I ever had a full breakdown over something incredibly small and then described it as 'a lot going on right now'",
      "Never have I ever asked for a 'small piece' of something and then taken a large piece",
      "Never have I ever changed my order at a restaurant because I heard someone else's order and it sounded better",
      "Never have I ever read a horoscope, thought it was wrong, then found a different one that said what I wanted",
      "Never have I ever lowered my standards for someone and then acted surprised when they met them exactly",
      "Never have I ever told someone I was almost there while simultaneously putting on shoes",
      "Never have I ever silently judged someone's playlist and later caught myself humming one of those songs",
      "Never have I ever accepted a meeting invite I had no intention of attending",
      "Never have I ever pretended to know a film everyone was referencing and nodded the whole time",
      "Never have I ever walked into a room, forgotten why, walked out, walked back in, and still not remembered",
      "Never have I ever said 'I'll sleep early tonight' at 11pm and opened Instagram at 2am",
      "Never have I ever sent a complaint email to a company with zero expectation of a reply and then been shocked when they replied",
      "Never have I ever committed to a new habit for exactly three days and then never discussed it again",
      "Never have I ever told a story that was 90% embellished and 10% true and believed it myself by the end",
      "Never have I ever avoided someone at a mall by pretending to be very interested in a store I would never enter",
      "Never have I ever chosen the long route somewhere because the short route meant passing someone I wasn't ready to deal with",
      "Never have I ever said 'I don't care about social media' while checking social media",
      "Never have I ever broken something at someone else's house and moved it so it looked like it was already like that",
      "Never have I ever rehearsed a resignation speech and then not resigned",
      "Never have I ever added something to my resume that was technically true but required a very charitable reading",
      "Never have I ever pretended to find something funny until everyone else was done laughing and then asked what happened",
      "Never have I ever sent a 'haha' reply when the correct response was zero reaction",
      "Never have I ever used 'my phone died' as an excuse when my phone was at 62%",
      "Never have I ever looked directly at someone walking towards me, panicked, and looked at my phone until they passed",
      "Never have I ever made a decision entirely based on which option required less talking to people",
      "Never have I ever eaten the last of something and put the empty container back in the fridge",
      "Never have I ever left a voicemail and then sent a text immediately saying 'hey just left a voicemail'",
      "Never have I ever said 'I'll just have one' and meant it"
    ],

    risque: [
      "Never have I ever developed feelings for someone in this room and never said anything",
      "Never have I ever sent a text to the absolute wrong person and considered faking my own death",
      "Never have I ever kissed someone at a function where I was 100% not supposed to be kissing anyone",
      "Never have I ever made eye contact with someone across the room at a party and both immediately knew what was happening",
      "Never have I ever had a 'what are we' conversation and walked away more confused than before",
      "Never have I ever stalked an ex so deep I accidentally liked a photo from 2019 and had to leave the country mentally",
      "Never have I ever been in a situationship so long I had to google when it became a relationship",
      "Never have I ever told someone I was 'not looking for anything serious' while being the most serious person in that room",
      "Never have I ever had feelings for someone's partner and handled it by simply not handling it",
      "Never have I ever matched with someone I knew in real life on a dating app and pretended it didn't happen to both our faces",
      "Never have I ever drunkenly texted someone something true and blamed it on being drunk",
      "Never have I ever cancelled plans with someone to make plans with someone else and then cancelled those plans too",
      "Never have I ever constructed an entire fake future with someone in my head before the second date",
      "Never have I ever been ghosted so cleanly I had to check if the person still existed",
      "Never have I ever shown my friends a screenshot asking 'what does this mean' when I knew exactly what it meant",
      "Never have I ever made a decision entirely based on astrology and refused to acknowledge that I did that",
      "Never have I ever liked someone more because they were unavailable and then had no idea what to do when they became available",
      "Never have I ever been caught snooping and somehow made the other person feel bad about it",
      "Never have I ever had a 'we're just talking' phase that lasted longer than most people's actual relationships",
      "Never have I ever been in a group chat where two people were clearly flirting and everyone was pretending not to notice",
      "Never have I ever written a long heartfelt message, read it back, and sent 'hey' instead",
      "Never have I ever dated someone who was clearly wrong for me, told no one, and introduced them at a party as 'a friend'",
      "Never have I ever left someone on delivered for 3 days because I needed to think, and then replied 'haha yeah'",
      "Never have I ever told someone I was over them while listening to a playlist I made specifically about them",
      "Never have I ever had a whole relationship end via text and acted like it was fine because I saw it coming",
      "Never have I ever been the person someone was cheating with and found out later and had to process that alone",
      "Never have I ever said 'I'm not jealous' and immediately checked their Instagram after",
      "Never have I ever run into someone I was avoiding and had to improvise an entire personality on the spot",
      "Never have I ever been attracted to someone I genuinely could not explain to any of my friends",
      "Never have I ever received a breakup speech I had completely written myself two weeks earlier in my head",
      "Never have I ever started talking to someone new specifically to get over someone else and then liked the new person less",
      "Never have I ever said 'it's fine, we're just friends' about someone it was absolutely not fine about",
      "Never have I ever been in love and decided not to say anything and have zero regrets",
      "Never have I ever had a secret that I'm still keeping from everyone in this room",
      "Never have I ever made out with someone, fully known it was a mistake, and still not regretted it",
      "Never have I ever been someone's 'phase' and figured it out too late",
      "Never have I ever liked a photo on Instagram as a signal and then acted innocent when they responded",
      "Never have I ever had feelings for someone and decided the friendship was too important — and then lost both",
      "Never have I ever cried about someone I was never officially with",
      "Never have I ever been more emotionally invested in a situationship than I was in an actual relationship"
    ]
  },

  // ──────────────────────────────────────────────
  // GAME 2: MAJORITY RULES — VOTE & DRINK
  // ──────────────────────────────────────────────
  majorityRules: {
    name: "Majority Rules",
    tagline: "Vote & Drink",
    emoji: "🗳️",
    color: "#7B2FF7",

    safe: [
      { question: "Who would last the longest on a reality show before having a complete breakdown on camera?", type: "person" },
      { question: "Who here is most likely to accidentally become famous for something embarrassing?", type: "person" },
      { question: "Who would survive a family WhatsApp group the longest before muting it forever?", type: "person" },
      { question: "Who would unironically go on Bigg Boss and think they'd win?", type: "person" },
      { question: "Who here is the most likely to have a full argument with a stranger on Instagram?", type: "person" },
      { question: "Who would negotiate the hardest at a street stall over something that costs ₹20?", type: "person" },
      { question: "Who in this group genuinely thinks they can cook but cannot?", type: "person" },
      { question: "Who here has definitely cried in a bathroom at a party and then come back acting completely fine?", type: "person" },
      { question: "Who would be the first to get kicked out of an IRCTC queue for arguing?", type: "person" },
      { question: "Who gives unsolicited advice with the confidence of someone who has never taken advice in their life?", type: "person" },
      { question: "Who would pitch a startup on Shark Tank with full confidence and zero market research?", type: "person" },
      { question: "Who here would finish the free bread basket before the waiter takes the order?", type: "person" },
      { question: "Who is most likely to overshare to a stranger on a flight and consider them a best friend by landing?", type: "person" },
      { question: "Who would call the restaurant to complain after already leaving a 1-star review?", type: "person" },
      { question: "Who here has a Notes app entry they will take to their grave?", type: "person" },
      { question: "Who would be the most dramatically useless in an actual emergency?", type: "person" },
      { question: "Who in this room is running from something right now?", type: "person" },
      { question: "Who is most likely to cancel plans and then post Instagram stories of what they were doing instead?", type: "person" },
      { question: "Who would make it to a second round of Indian Idol purely on confidence?", type: "person" },
      { question: "Who has definitely rehearsed what they'd say if they ever met Shah Rukh Khan?", type: "person" },
      { question: "Who would buy a flight ticket to a destination with absolutely no plan?", type: "person" },
      { question: "Who here Googles their own name more than they'd admit?", type: "person" },
      { question: "Who would take 400 photos on a trip and post exactly two?", type: "person" },
      { question: "Who in this group has a situationship they haven't told anyone about?", type: "person" },
      { question: "Who here would actually be fine with 48 hours and no phone?", type: "person" },
      { question: "Who would be the first person to get scammed by a 'you've won a prize' email?", type: "person" },
      { question: "Who has the most toxic relationship with their own to-do list?", type: "person" },
      { question: "Who would make the worst roommate but somehow convince you they'd be great before you moved in?", type: "person" },
      { question: "Who is most likely to text 'we need to talk' and then refuse to say what it's about?", type: "person" },
      { question: "Who here has a whole personality they only use at work that no one in this room has ever seen?", type: "person" },
      { question: "Who would start a group chat for a plan that never happens and then never archive the chat?", type: "person" },
      { question: "Who is most likely to be the main character of a very stressful sitcom?", type: "person" },
      { question: "Who here has said 'I'm not a morning person' as a personality trait for over 5 years?", type: "person" },
      { question: "Who would confidently order for the table and get it completely wrong?", type: "person" },
      { question: "Who in this group has the most detailed opinion about something that doesn't affect them at all?", type: "person" },
      { question: "Who would be the last to admit they were wrong even when presented with literal evidence?", type: "person" },
      { question: "Who here sends the longest voice notes?", type: "person" },
      { question: "Who is most likely to be running 3 unfinished courses on an app they paid for?", type: "person" },
      { question: "Who would cry at a Vodafone ad but not at a funeral?", type: "person" },
      { question: "Who here uses their horoscope to avoid accountability?", type: "person" },
      { question: "Who is most likely to still be awake at 3am on a Tuesday for no reason?", type: "person" },
      { question: "Who here would join a multilevel marketing scheme and try to recruit people in this room?", type: "person" },
      { question: "Who is most likely to have strong opinions about someone's relationship they have never been in a relationship with?", type: "person" },
      { question: "Who would describe their attachment style in a dating app bio?", type: "person" },
      { question: "Who is most likely to ghost a group project and show up for the presentation?", type: "person" },
      { question: "Who here has definitely vented to one person in this room about another person in this room?", type: "person" },
      { question: "Who would take the longest to respond but be the first to see the message?", type: "person" },
      { question: "Who is most likely to have bought a self-help book and read exactly 40 pages?", type: "person" },
      { question: "Who would get into an argument on a comment section and refuse to let it go?", type: "person" },
      { question: "Who here has the most elaborate excuses for the simplest things?", type: "person" }
    ],

    risque: [
      { question: "Who here has the best game when they're drunk versus when they're sober?", type: "person" },
      { question: "Who in this room is most likely to fall in love with the wrong person and know it immediately?", type: "person" },
      { question: "Who has the most chaotic romantic history in this group?", type: "person" },
      { question: "Who here looks like they have it together but their DMs tell a completely different story?", type: "person" },
      { question: "Who would be the most dangerous person to give a tequila shot to right now?", type: "person" },
      { question: "Who here has a type that is clearly a red flag but keeps going back anyway?", type: "person" },
      { question: "Who in this group has sent a text tonight they haven't told anyone about?", type: "person" },
      { question: "Who is definitely going to do something chaotic before this night is over?", type: "person" },
      { question: "Who here is most likely to have feelings for someone in this room right now?", type: "person" },
      { question: "Who would make the worst decisions on a solo trip to Goa?", type: "person" },
      { question: "Who in this room would fall for someone just because they were mean to them?", type: "person" },
      { question: "Who here has drafted a text, deleted it, redrafted it, and still hasn't sent it?", type: "person" },
      { question: "Who is most likely to say 'I don't care' and then care the absolute most?", type: "person" },
      { question: "Who in this group has a secret that would change how everyone sees them?", type: "person" },
      { question: "Who here would be most honest about their feelings if they had one more drink?", type: "person" },
      { question: "Who is most likely to have a work crush they have absolutely not mentioned?", type: "person" },
      { question: "Who here has the most complicated relationship with their ex?", type: "person" },
      { question: "Who would slide into a DM tonight if no one was watching?", type: "person" },
      { question: "Who in this room is currently in denial about something romantic?", type: "person" },
      { question: "Who is most likely to end up in a situation tonight that they'll explain for the next three months?", type: "person" },
      { question: "Who here has been in love and never said it?", type: "person" },
      { question: "Who would be the most brutally honest about their exes if we asked right now?", type: "person" },
      { question: "Who in this group is someone else's situationship right now without fully knowing it?", type: "person" },
      { question: "Who here has the most questionable 3am decision-making history?", type: "person" },
      { question: "Who is most likely to date someone from this group within the next year?", type: "person" },
      { question: "Who here is carrying a torch for someone that everyone else has moved on from?", type: "person" },
      { question: "Who would survive a 'no contact' rule the shortest amount of time?", type: "person" },
      { question: "Who in this room has the most power over someone else in this room without knowing it?", type: "person" },
      { question: "Who here has had a conversation with someone tonight that had a completely different subtext?", type: "person" },
      { question: "Who is most likely to be someone's favourite person that they refuse to admit?", type: "person" }
    ]
  },

  // ──────────────────────────────────────────────
  // GAME 3: BOLLYWOOD BLITZ — SPEED TRIVIA
  // ──────────────────────────────────────────────
  bollywoodBlitz: {
    name: "Bollywood Blitz",
    tagline: "Speed Trivia",
    emoji: "🎬",
    color: "#00C9A7",
    timerSeconds: 15,

    safe: [
      { question: "What was the name of the dog in Hum Aapke Hain Koun?", answer: "Tuffy" },
      { question: "Which film gave us 'Bole chudiyan, bole kangna'?", answer: "Kabhi Khushi Kabhie Gham (K3G)" },
      { question: "Which villain did Shah Rukh Khan play in a 1993 Yash Chopra film?", answer: "Darr — he played Rahul the obsessive stalker" },
      { question: "Who directed Dil Dhadakne Do?", answer: "Zoya Akhtar" },
      { question: "What is Poo's real name in K3G?", answer: "Pooja Sharma, played by Kareena Kapoor" },
      { question: "Which film has 'Dola Re Dola' with Aishwarya and Madhuri?", answer: "Devdas (2002)" },
      { question: "Complete: 'Tum paas aaye, yun muskuraye...'", answer: "Kuch Kuch Hota Hai title song" },
      { question: "Name the film: 'Picture abhi baaki hai mere dost'", answer: "Om Shanti Om" },
      { question: "Which film had the character Mogambo?", answer: "Mr. India" },
      { question: "Who played Geet in Jab We Met?", answer: "Kareena Kapoor" },
      { question: "Name the director of Gangs of Wasseypur.", answer: "Anurag Kashyap" },
      { question: "What does RRR stand for?", answer: "Roudram Ranam Rudhiram" },
      { question: "Which actress played Begum Para in Heeramandi?", answer: "Manisha Koirala" },
      { question: "Which 2009 film has Ranbir Kapoor playing a musician named Jordan?", answer: "Rockstar (2011 — accept it)" },
      { question: "In 3 Idiots what was Rancho's real name?", answer: "Phunsukh Wangdu / Chhanchhad — accept either" },
      { question: "Name the South Indian film that became the biggest Hindi-dubbed blockbuster recently.", answer: "RRR or KGF Chapter 2 — accept both" },
      { question: "What was the sequel to Baahubali called?", answer: "Baahubali 2: The Conclusion" },
      { question: "Which film starred Deepika as Leela and Ranveer as Ram?", answer: "Goliyon Ki Raasleela Ram-Leela" },
      { question: "Who sang Jai Ho for Slumdog Millionaire?", answer: "Sukhwinder Singh, composed by A.R. Rahman" },
      { question: "Which Alia Bhatt film was shot almost entirely on a highway?", answer: "Highway" },
      { question: "Name the director behind Lagaan.", answer: "Ashutosh Gowariker" },
      { question: "Complete: 'Kuch kuch hota hai, Rahul, tum...'", answer: "nahi samjhoge" },
      { question: "Which actress won a Filmfare for Gangubai Kathiawadi?", answer: "Alia Bhatt" },
      { question: "Name the film where Amitabh Bachchan played a blind pianist.", answer: "Black" },
      { question: "What is the name of the award show starting with F that Bollywood celebrates every year?", answer: "Filmfare Awards" },
      { question: "In ZNMD, which three adventure activities do the friends do?", answer: "Skydiving, scuba diving, running with the bulls (Tomatina festival)" },
      { question: "Which actor plays Kabir in Dil Dhadakne Do?", answer: "Ranveer Singh" },
      { question: "Name the OTT show set in Panchayat secretariat of a UP village.", answer: "Panchayat" },
      { question: "Which film has the song Chaiyya Chaiyya performed on a moving train roof?", answer: "Dil Se (1998)" },
      { question: "Name the Sanjay Leela Bhansali film that starred Salman Khan, Aishwarya Rai, and Ajay Devgn.", answer: "Hum Dil De Chuke Sanam" },
      { question: "Complete the lyric: 'Tujhe dekha toh yeh jaana sanam...'", answer: "Pyaar hota hai deewana sanam" },
      { question: "Who played the villain in Krrish 3?", answer: "Vivek Oberoi as Kaal" },
      { question: "Which 2023 film had Ranveer Singh in a very controversial role that divided everyone?", answer: "Rocky Aur Rani Kii Prem Kahaani or Animal depending on interpretation — accept both" },
      { question: "Name the actress who played Naina in Kal Ho Naa Ho.", answer: "Preity Zinta" },
      { question: "Which film gave us the dialogue 'Don ko pakadna mushkil hi nahin, namumkin hai'?", answer: "Don (1978) and remade in 2006 with Shah Rukh Khan" },
      { question: "Name the director of Dil Chahta Hai.", answer: "Farhan Akhtar" },
      { question: "Which city is the primary setting of Yeh Jawaani Hai Deewani?", answer: "Manali for the beginning, Udaipur for the wedding — accept either" },
      { question: "What was Mirzapur's lead character's name?", answer: "Akhandanand Tripathi, called Kaleen Bhaiya — played by Pankaj Tripathi" },
      { question: "Which film has the song Ae Dil Hai Mushkil as its title?", answer: "Ae Dil Hai Mushkil (2016), directed by Karan Johar" },
      { question: "Who directed the original Sholay?", answer: "Ramesh Sippy" },
      { question: "Name the actress who played Silk Smitha in The Dirty Picture.", answer: "Vidya Balan" },
      { question: "Which 2014 film had Aamir Khan playing a Bollywood character who couldn't drink alcohol?", answer: "PK — he was an alien, not a Bollywood character. Accept PK" },
      { question: "What was the name of the fictional cricket team in Lagaan?", answer: "There's no team name — it's just the villagers of Champaner" },
      { question: "Which Bollywood film is set entirely on a train?", answer: "Jab Tak Hai Jaan has train scenes, but the best answer is Dil Se or Bunty Aur Babli. Accept any" },
      { question: "Name the actor who played Bhiku Mhatre in Satya.", answer: "Manoj Bajpayee" },
      { question: "Which song from Dilwale has Shah Rukh and Kajol in Iceland?", answer: "Gerua" },
      { question: "Name the real-life person Aligarh (2015) is based on.", answer: "Professor Siras, Ramchandra Siras" },
      { question: "Who played young Sarkar in Sarkar Raj?", answer: "Abhishek Bachchan played Shankar in Sarkar — accept that" },
      { question: "Which Bollywood film has a character obsessed with Aamir Khan?", answer: "Fan (2016) had a character obsessed with Shah Rukh Khan. Correct answer: Fan" },
      { question: "Name the Netflix series that follows a Delhi crime beat reporter.", answer: "Delhi Crime" }
    ],

    risque: [
      { question: "Which real-life Bollywood couple broke up and both made films about heartbreak?", answer: "Ranbir Kapoor and Deepika Padukone — Tamasha, Ae Dil Hai Mushkil, Yeh Jawaani Hai Deewani" },
      { question: "Name a Bollywood film that got cut by the censor board for being too bold.", answer: "Udta Punjab, Lipstick Under My Burkha, Paanch — accept any" },
      { question: "Which item number made Sunny Leone a Bollywood name?", answer: "Baby Doll in Ragini MMS 2" },
      { question: "Which 2023 film was accused of glorifying toxic masculinity but became a massive hit anyway?", answer: "Animal, directed by Sandeep Reddy Vanga" },
      { question: "Which Bollywood film was the first to portray a same-sex relationship seriously?", answer: "Aligarh (2015), directed by Hansal Mehta" },
      { question: "Name the streaming show that made all of India have a very uncomfortable conversation about relationships.", answer: "Made in Heaven — accept any with reasoning" },
      { question: "Which Bollywood song was banned or restricted for being objectionable but hit No.1 anyway?", answer: "Fevicol Se, Munni Badnaam, Laila Main Laila — accept any" },
      { question: "Name a Bollywood actor who played a negative role so convincingly people thought they were actually like that.", answer: "Shah Rukh Khan in Darr and Baazigar. Accept any" },
      { question: "Which Netflix India original had the most explicit content and still got a sequel?", answer: "Mirzapur — accept any with confidence" },
      { question: "Name the Bollywood biopic about a sex worker that won Vidya Balan a National Award.", answer: "The Dirty Picture — she won Filmfare, not National Award. Accept The Dirty Picture" },
      { question: "Which real-life Bollywood affair became public knowledge when a paparazzi photo broke the internet?", answer: "Ranbir Kapoor and Katrina Kaif in Ibiza — accept any" },
      { question: "Name the film that had an intimate scene so talked-about the director had to comment on it publicly.", answer: "Kabir Singh, Animal, Gehraiyaan — accept any with reasoning" },
      { question: "Which actress said in an interview that she had no issues with bold scenes and then delivered?", answer: "Deepika Padukone in Gehraiyaan — accept any" },
      { question: "Name the Bollywood remake of a South film that was more risque than the original.", answer: "Ek Hasina Thi, Murder series — accept any" },
      { question: "Which 2022 film had Deepika Padukone in an intimate scene that trended for days?", answer: "Gehraiyaan, directed by Shakun Batra" },
      { question: "Name the OTT series that explored polyamory in an Indian context for the first time.", answer: "Four More Shots Please, Modern Love Mumbai — accept any" },
      { question: "Which Bollywood director is known for making films where the male lead is deeply problematic but framed as romantic?", answer: "Sandeep Reddy Vanga — Kabir Singh, Animal" },
      { question: "Name a Bollywood film set in a brothel that won critical acclaim.", answer: "Devdas, Chameli, Mandi — accept any" },
      { question: "Which actress turned down a Sanjay Leela Bhansali film for being 'too bold' and later regretted it publicly?", answer: "Open answer — accept any with a story" },
      { question: "Name the song from Lust Stories or Ghost Stories that became a meme.", answer: "Electric in Lust Stories 2 — accept any" }
    ]
  },

  // ──────────────────────────────────────────────
  // DARE PILE — shared across all games via spin the bottle
  // ──────────────────────────────────────────────
  dares: {
    safe: [
      "Do your most convincing impression of an Indian mom finding out her child got a B grade. 30 seconds. Go.",
      "Call someone in your contacts right now, say 'we need to talk' completely seriously, then hang up after 5 seconds.",
      "Narrate what is happening in this room right now in the voice of a Bollywood film trailer.",
      "Do the hook step from Chaiyya Chaiyya. Everyone must clap. No skipping.",
      "Give a 45-second TED Talk on why your astrological sign explains everything wrong in your life.",
      "Text your mom a random Salman Khan dialogue right now and show the group her response.",
      "Describe your last situationship using only the titles of Bollywood films.",
      "Recreate the DDLJ train scene with the person sitting next to you. No exceptions.",
      "Do a full Filmfare award speech thanking everyone for your performance in 'Not Having My Life Together'.",
      "Read out your most unhinged Notes app entry from the last 6 months. All of it.",
      "In your best aunty voice, give marriage advice to the person across from you.",
      "Say one completely honest thing about the person to your left. They cannot respond for 30 seconds.",
      "Rank everyone in this room by who you think has the most chaotic personal life. Explain your reasoning.",
      "Show the group the last three things you searched on YouTube.",
      "Do a full hair flip and runway walk to the nearest wall and back. You are a star.",
      "Describe your type in 3 words. The group decides if those 3 words describe you or someone who would destroy you.",
      "Do your best impression of a Zoom call on bad Wi-Fi. 'Hello? Can you hear me— sorry you were—'",
      "Read out the last 5 lines of your most recent WhatsApp conversation. No names needed.",
      "Act out what you do when you're alone in the house for the first time in days. Be honest.",
      "Do an impression of this group's most dramatic person telling a story. No names. They'll know.",
      "Reenact the last time you lied to your parents. Include the face you made.",
      "Sing the first song that comes to mind in the voice of a 90s Bollywood hero. Full emotion.",
      "Give a 30-second speech on why you deserve to win an award for 'Most Complicated Person in This Room'.",
      "Show everyone your camera roll from exactly 6 months ago. No skipping.",
      "Tell the group your most embarrassing autocorrect fail. Read it out exactly.",
      "Do a dramatic slow-motion walk across the room while everyone hums a Bollywood background score.",
      "Imitate the person to your right ordering food at a fancy restaurant they've never been to.",
      "Tell the group one thing you bought online that you've never told anyone about.",
      "Do your best impression of the group's most wholesome member trying to be intimidating.",
      "Give a motivational speech in the style of a desi dad who means well but doesn't understand anything.",
      "Pick someone in the room and describe their vibe as a Bollywood character. Be specific.",
      "Without saying any names, describe the most chaotic person you know. Group guesses who it is.",
      "Perform the 'log kya kahenge' speech your inner aunty gives you every time you do something fun.",
      "Text your closest contact outside this room 'I have something to tell you' and show the group their panic reply.",
      "Tell the group what your first impression was of the person directly across from you. No softening it.",
      "Do a news anchor voice and report on what's happening in this room right now as breaking news.",
      "Rate everyone's fashion tonight out of 10. Publicly. With reasoning.",
      "Describe the last awkward situation you were in as if it was a scene from a film. Include the background score."
    ],
    risque: [
      "Tell the group one thing you've never told anyone in this room. It has to be something real.",
      "Show the last person you texted and the message. Blur the name, not the content.",
      "Point at the person in this room you'd be most terrified to be stuck in a lift with for 2 hours. Explain.",
      "Read out the last DM you sent to someone you were interested in. Word for word.",
      "Tell the person across from you one genuine thing you think about them. Not necessarily a compliment. Just honest.",
      "The group picks a contact in your phone. You send them a voice note right now saying 'I've been thinking about you lately'.",
      "Describe your most recent romantic situation in 3 sentences. The group rates its chaos out of 10.",
      "Show the last photo you took on your phone. Your face will explain everything.",
      "Tell the group what your last 'I'm fine' was actually about.",
      "Show your Spotify most played song and explain why without lying.",
      "Tell everyone your honest first impression of the last person you went on a date with.",
      "Read out the most dramatic paragraph from your last major argument over text. No names needed.",
      "Show the group the most recent photo of someone you've been thinking about. No context required.",
      "Tell the group one thing you find attractive that you've never admitted out loud.",
      "Describe in one sentence the most complicated feeling you currently have about someone in this room.",
      "Point at the person here you think has the most interesting romantic life that they never talk about.",
      "Tell the group the last time you did something you knew was a bad idea and did it anyway.",
      "The group picks someone to call from your contacts. You say 'I was just thinking about you' and hang up.",
      "Tell everyone one thing that happened tonight you've already been overthinking.",
      "Rank the people in this room by who you'd trust with a secret. Explain the bottom of the list."
    ]
  }
};
